### ISSUE TITLE
Fix color scheme creater GUI

### ISSUE THREAD

**Issue by Sierrasch** [UCSB-CS56-Projects/cs56-discretemath-towers-sierpinski#44]
Currently the color scheme creator GUI (run using ant EX_GUI) is very confusing and not aesthetically pleasing. Fix the layout of the window to make it more logical, make the instructions clearer, and clean up the look of the window to make it more navigable and user friendly.

**Comment by Sierrasch** [comment]
fixed in commit b9df89e on Mar 3, 2016 ~estimated 125 points

**Comment by ashedden** [comment]
Approved!
